#!/usr/bin/env bash
#
#   ./bootstrap.sh      ask for values, then switch
#   ./bootstrap.sh -y   take the defaults
#
# shellcheck disable=SC1090,SC2154

set -euo pipefail

# ── Output ────────────────────────────────────────────────────────────

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() {
  printf '\033[1;31merror:\033[0m %s\n' "$*" >&2
  exit 1
}

assume_yes=false
[ "${1:-}" = "-y" ] && assume_yes=true

confirm() {
  $assume_yes && return 0
  local reply=""
  read -r -p "$1 [y/N]: " reply || true
  case "$reply" in [yY] | [yY][eE][sS]) return 0 ;; *) return 1 ;; esac
}

# ask <var> <prompt> <default>
ask() {
  $assume_yes && {
    printf -v "$1" '%s' "$3"
    printf '%s: %s\n' "$2" "$3"
    return 0
  }
  local reply=""
  if [ -n "$3" ]; then
    read -r -p "$2 [$3]: " reply || true
    reply=${reply:-$3}
  else
    while [ -z "$reply" ]; do read -r -p "$2: " reply || true; done
  fi
  printf -v "$1" '%s' "$reply"
}

nix_list() {
  local out="" word
  for word in $1; do out+=" \"$word\""; done
  printf '[%s ]' "$out"
}

# ── Requirements ──────────────────────────────────────────────────────

[ "$(uname -s)" = "Darwin" ] || die "macOS only."

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
machine_nix="$repo_root/machine.nix"

case "$repo_root" in
"$HOME"/*) config_dir=${repo_root#"$HOME"/} ;;
*) die "Keep this repository under $HOME. Current location: $repo_root" ;;
esac

case "$(uname -m)" in
arm64) host_platform="aarch64-darwin" ;;
x86_64) host_platform="x86_64-darwin" ;;
*) die "Unsupported architecture: $(uname -m)" ;;
esac

# ── Xcode Command Line Tools ──────────────────────────────────────────

if xcode-select -p >/dev/null 2>&1; then
  info "Xcode Command Line Tools: already installed"
else
  info "Installing Xcode Command Line Tools (a GUI dialog opens)"
  xcode-select --install || true
  until xcode-select -p >/dev/null 2>&1; do sleep 10; done
  info "Xcode Command Line Tools: done"
fi

# ── Nix ───────────────────────────────────────────────────────────────

nix_profile=/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
# Not on PATH yet right after the install
[ -f "$nix_profile" ] && . "$nix_profile"

if command -v nix >/dev/null 2>&1; then
  info "Nix: already installed ($(command -v nix))"
else
  info "Nix is missing; running the official multi-user installer"
  confirm "Run https://nixos.org/nix/install in daemon mode?" ||
    die "Nix is required."
  sh <(curl -L https://nixos.org/nix/install) --daemon
  [ -f "$nix_profile" ] && . "$nix_profile"
  command -v nix >/dev/null 2>&1 || die "Nix is installed but not on PATH. Re-run from a new shell."
fi

nix_flags=(--extra-experimental-features "nix-command flakes")

# ── Values ────────────────────────────────────────────────────────────

from_machine() {
  [ -f "$machine_nix" ] || return 0
  nix "${nix_flags[@]}" eval --raw --file "$machine_nix" --apply "$1" 2>/dev/null || true
}

this_host=$(scutil --get LocalHostName 2>/dev/null || hostname -s)
default_hosts=$(from_machine 'm: builtins.concatStringsSep " " m.hostnames')
# Append, so one machine.nix covers several machines
case " $default_hosts " in
*" $this_host "*) ;;
*) default_hosts=$(printf '%s %s' "$default_hosts" "$this_host" | sed 's/^ *//') ;;
esac

default_users=$(from_machine 'm: builtins.concatStringsSep " " m.usernames')
[ -n "$default_users" ] || default_users=$(id -un)

echo
info "Settings for this machine (written to machine.nix, kept out of git)"
echo "  clone path   ~/$config_dir  (taken from this script's location)"
echo "  platform     $host_platform"
echo

ask hostnames "Hostnames that --flake may omit the attribute for (space-separated)" "$default_hosts"
ask usernames "Usernames to apply this configuration to (space-separated, first is primaryUser)" "$default_users"

primary_user=${usernames%% *}

for user in $usernames; do
  id -u "$user" >/dev/null 2>&1 || warn "User '$user' does not exist on this machine; switch may fail."
done

# ── machine.nix ───────────────────────────────────────────────────────

info "Writing machine.nix"
cat >"$machine_nix" <<EOF
# Generated by bootstrap.sh, untracked.
{
  hostnames = $(nix_list "$hostnames");
  usernames = $(nix_list "$usernames");

  configDir = "$config_dir";
  hostPlatform = "$host_platform";
}
EOF

if ! git -C "$repo_root" check-ignore -q machine.nix 2>/dev/null; then
  info "Adding machine.nix to .gitignore"
  printf '\n# bootstrap.sh generated files\nmachine.nix\n' >>"$repo_root/.gitignore"
fi

# ── git identity ──────────────────────────────────────────────────────

# ~/.config/git/config is a read-only link, so `git config --global` fails
git_local="$HOME/.config/git/config.local"

from_git_local() { git config -f "$git_local" --get "$1" 2>/dev/null || true; }

default_git_name=$(from_git_local user.name)
[ -n "$default_git_name" ] || default_git_name=$(git config --get user.name 2>/dev/null || true)

default_git_email=$(from_git_local user.email)
[ -n "$default_git_email" ] || default_git_email=$(git config --get user.email 2>/dev/null || true)

echo
info "git identity (written to $git_local, kept out of git)"
echo

ask git_name "Name for commits (user.name)" "$default_git_name"
ask git_email "Email for commits (user.email)" "$default_git_email"

if [ -n "$git_name" ] && [ -n "$git_email" ]; then
  mkdir -p "$(dirname "$git_local")"
  if [ ! -e "$git_local" ]; then
    cat >"$git_local" <<'EOF'
; Generated by bootstrap.sh.
EOF
  fi
  info "Writing user.name / user.email to $git_local"
  git config -f "$git_local" user.name "$git_name"
  git config -f "$git_local" user.email "$git_email"
else
  warn "user.name or user.email is empty; leaving $git_local alone (commits will fail)."
fi

# ── Homebrew ──────────────────────────────────────────────────────────

# nix-homebrew installs brew; this only hands the prefix to primaryUser
brew_prefix=/opt/homebrew
[ "$host_platform" = "x86_64-darwin" ] && brew_prefix=/usr/local/Homebrew

if [ -d "$brew_prefix" ]; then
  brew_owner=$(stat -f '%Su' "$brew_prefix")
  if [ "$brew_owner" = "$primary_user" ]; then
    info "Homebrew: $brew_prefix is already owned by $primary_user"
  else
    info "Homebrew: moving $brew_prefix from $brew_owner to $primary_user (for autoMigrate)"
    sudo chown -R "$primary_user:admin" "$brew_prefix"
  fi
else
  info "Homebrew: not installed; nix-homebrew installs it during switch"
fi

# ── /etc handover ─────────────────────────────────────────────────────

# nix-darwin refuses to overwrite /etc files it did not write
for f in /etc/zshrc /etc/bashrc; do
  [ -f "$f" ] || continue
  grep -q "nix-darwin" "$f" 2>/dev/null && continue
  [ -e "$f.before-nix-darwin" ] && continue
  info "Moving $f to $f.before-nix-darwin"
  sudo mv "$f" "$f.before-nix-darwin"
done

# ── switch ────────────────────────────────────────────────────────────

# `path:` so the flake can see the untracked machine.nix
flake_ref="path:$repo_root#default"

echo
info "Command to apply: sudo darwin-rebuild switch --flake $flake_ref"
confirm "Run switch?" || {
  echo "Aborted. To apply it later by hand:"
  echo "  sudo darwin-rebuild switch --flake $flake_ref"
  exit 0
}

if command -v darwin-rebuild >/dev/null 2>&1; then
  sudo darwin-rebuild switch --flake "$flake_ref"
else
  info "darwin-rebuild is not available yet; calling nix-darwin directly (first run)"
  sudo nix "${nix_flags[@]}" run nix-darwin/master#darwin-rebuild -- switch --flake "$flake_ref"
fi

echo
info "Done. Open a new shell to pick up the changes."
